require 'rake/testtask'

Rake::TestTask.new do |t|
  t.verbose = true
  t.libs << "test"
  t.test_files = FileList['test/**/**/*_test.rb']
end

task :default => 'test'

# Dir.glob('lib/tasks/**/*.rake').each { |rakefile| import rakefile }