guard 'sass',         input: 'assets/app/stylesheets',  output: 'public/stylesheets'
guard 'coffeescript', input: 'assets/app/javascripts',  output: 'public/javascripts'

guard 'livereload' do
  watch("app/api.rb")
  watch(%r{app/views/.+\.(erb|haml|slim)})
  watch(%r{app/helpers/.+\.rb})
  watch(%r{public/.+\.(css|js|html)})
  # watch(%r{config/locales/.+\.yml})
end
